#!/bin/bash

echo "WATCH BUILD STATUS"

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
echo "DIR"$DIR
cd $DIR

PLISTBUDDY="/usr/libexec/PlistBuddy"
InfoPlistPath="./watchbuilds.plist"

BUILD_ID=$(/usr/libexec/PlistBuddy -c "Print :JobBuildId" "${InfoPlistPath}")
BUNDLE_ID=$(/usr/libexec/PlistBuddy -c "Print :bundleIdentifier" "${InfoPlistPath}")
POST_URL=$(/usr/libexec/PlistBuddy -c "Print :posturl" "${InfoPlistPath}")
APP_NUM=$(/usr/libexec/PlistBuddy -c "Print :appBuildNumber" "${InfoPlistPath}")
USER_NAME=$(/usr/libexec/PlistBuddy -c "Print :username" "${InfoPlistPath}")
USER_PASSWORD=$(/usr/libexec/PlistBuddy -c "Print :password" "${InfoPlistPath}")

echo $BUNDLE_ID
echo $BUILD_ID
echo $POST_URL
echo $APP_NUM
echo $USER_NAME


export FASTLANE_PASSWORD=$USER_PASSWORD

watchbuild -a $BUNDLE_ID -u piyushaggarwal.incedo@gmail.com

postBuildStatus(){ #buildid, posturl, status, errormsg
	echo "POSTING BUILD STATUS"
    BODY_DATA="{\"buildId\":$1,\"status\":\"$3\",\"errorMessage\":\"$4\",\"message\":\"$5\",\"percentComplete\":$6,\"buildVersion\":$7}"
    echo "\n**********BUILD_STATUS_UPDATE**********\nPOST_URL=$2\nBODY_DATA=["$BODY_DATA"]\n---------------------------------------"
    curl -H 'Content-Type: application/json' -X POST -d "$BODY_DATA" $2
}


$message="Build Has Been SuccessFully Processed By Apple Store and Test Flight"


echo $BUILD_ID
echo $BUNDLE_ID
echo ${message}
echo ${message}
echo $APP_NUM

postBuildStatus $BUILD_ID $POST_URL "SUCCESS_PLAY_STORE" "Build Has Been SuccessFully Processed By Apple Store and Test Flight" "Build Has Been SuccessFully Processed By Apple Store and Test Flight" 100 $APP_NUM





